### ISSUE TITLE
RHEL/Rocky/CentOS 8 enables PHP-FPM by default

### ISSUE THREAD

**Issue by enbrnz** [owncloud-ansible/php#15]
- Investigate whether there is a way to prevent that
- Do we want to support remi as well?
  - If not, can we display a warning?
  - If not, can we force app stream?
  - If yes, can we provide a switch between app stream and remi?
- TODO: better docs about usage with CentOS 8

**Comment by xoxys** [comment]
>     * Investigate whether there is a way to prevent that
> 
>     * Do we want to support remi as well?
>       
>       * If not, can we display a warning?
>       * If not, can we force app stream?

IMO Ansible roles are a just a blueprint/toolbox. We should not prevent anything. Everything that we defined in a role by providing a proper variable/tasks should be usable. The default config works out of the box, but an advanced user can always overwrite vars if they know how (and that's in my opinion one big advantage of Ansible).

>       * If yes, can we provide a switch between app stream and remi?

There is already a way to define a custom repo and packages regardless of the source. I think it's not a good idea to start implementing a logic to switch "automatically" between repos. The repos have to be available on the system. That need to be done by the system owner and can be scl, remi, self-hosted repo mirror or whatever. As long as it is available by the package manager Ansible can use it. You just need to adjust the package names (and maybe config paths) in the dependent role.

>     * TODO: better docs about usage with CentOS 8

That's the way to go. Define requirements and what's supported.

**Comment by enbrnz** [comment]
Solution:
Actually to fix in apache configuration: 
`/etc/httpd/conf.modules.d/00-mpm.conf`
switch from even to prefork

**Comment by enbrnz** [comment]
> Solution: Actually to fix in apache configuration: `/etc/httpd/conf.modules.d/00-mpm.conf` switch from event to prefork

I'm not 100% that is all, but that definitely has to happen.

**Comment by xoxys** [comment]
Seems to be all. Works for me after after switching back to prefork.
