### ISSUE TITLE
default_socket_timeout is not set

### ISSUE THREAD

**Issue by jnweiger** [owncloud-ansible/php#18]
We set max_execution_time to 3600 seconds, 
but default_socket_timeout remains at the system default. This is typically only 60 seconds.

Can lead to issues with e.g. ICAP connections.

**Comment by jnweiger** [comment]
We today agreed that 3600 is a good value for the default_socket_timeout. Thanks!

BTW: Our docker deployments have the same issue:

```
docker run  owncloud/server:latest grep socket_timeout '/etc/php/7.4/*/*'
/etc/php/7.4/apache2/php.ini:default_socket_timeout = 60
/etc/php/7.4/cli/php.ini:default_socket_timeout = 60
```

**Comment by xoxys** [comment]
Could you create a separate issue in `owncloud-docker/php`?
